AH_CATEGORY_MAP: dict[str, str] = {
    "groente-aardappelen":              "Vegetables & Fruits",
    "fruit-verse-sappen":               "Vegetables & Fruits",
    "maaltijden-salades":               "Ready Meals & Salads",
    "vlees":                            "Meat & Fish",
    "vis":                              "Meat & Fish",
    "vegetarisch-vegan-en-plantaardig": "Meat & Fish",
    "vleeswaren":                       "Meat & Fish",
    "kaas":                             "Cheese",
    "zuivel-eieren":                    "Dairy & Eggs",
    "bakkerij":                         "Bakery",
    "borrel-chips-snacks":              "Snacks & Chocolates",
    "koek-snoep-chocolade":             "Snacks & Chocolates",
    "pasta-rijst-wereldkeuken":         "Pantry & World Foods",
    "soepen-sauzen-kruiden-olie":       "Pantry & World Foods",
    "ontbijtgranen-beleg":              "Pantry & World Foods",
    "diepvries":                        "Frozen",
    "koffie-thee":                      "Coffee & Tea",
    "frisdrank-sappen-water":           "Soft Drinks",
    "bier-wijn-aperitieven":            "Beer & Wine",
    "drogisterij":                      "Drugstore & Health",
    "baby-en-kind":                     "Drugstore & Health",
    "huishouden":                       "Household",
    "huisdier":                         "Animals",
    "koken-tafelen-vrije-tijd":         "Home & Kitchenware",
    "GALL":                             "Beer & Wine",
    "GALLCARD":                         "Beer & Wine",
    "ETOS":                             "Drugstore & Health",
    # glutenvrij, ah-voordeelshop, AHONLINE are cross-category — left unmapped
}

JUMBO_CATEGORY_MAP: dict[str, str] = {
    "Aardappelen, groente en fruit":        "Vegetables & Fruits",
    "Verse maaltijden en gemak":            "Ready Meals & Salads",
    "Vlees, vis en vega":                   "Meat & Fish",
    "Brood en gebak":                       "Bakery",
    "Zuivel, boter en eieren":              "Dairy & Eggs",
    "Vleeswaren, kaas en tapas":            "Meat & Fish",
    "Vegetarisch en plantaardig":           "Meat & Fish",
    "Conserven, soepen, sauzen, oliën":     "Pantry & World Foods",
    "Wereldkeukens, kruiden, pasta en rijst": "Pantry & World Foods",
    "Ontbijt, broodbeleg en bakproducten":  "Pantry & World Foods",
    "Koek, snoep, chocolade en chips":      "Snacks & Chocolates",
    "Koffie en thee":                       "Coffee & Tea",
    "Frisdrank en sappen":                  "Soft Drinks",
    "Bier en wijn":                         "Beer & Wine",
    "Diepvries":                            "Frozen",
    "Drogisterij en gezondheid":            "Drugstore & Health",
    "Baby en kind":                         "Drugstore & Health",
    "Huishouden en dieren":                 "Household",
    "Non-food en servicebalie":             "Home Goods & Seasonal",
}
